- name: Проверка и настройка Docker
  hosts: office1_servers,office2_servers
  become: yes
  gather_facts: no

  vars:
    docker_package: docker.io
    docker_version: "26.1.3"

  tasks:
    - name: Убедиться, что нужная версия Docker установлена через apt
      ansible.builtin.apt:
        name: "{{ docker_package }}={{ docker_version }}"
        state: present
        update_cache: yes

    - name: Проверить наличие Docker через snap
      ansible.builtin.shell: snap list | grep docker
      register: docker_snap
      failed_when: false
      changed_when: false

    - name: Удалить Docker из snap, если установлен
      ansible.builtin.snap:
        name: docker
        state: absent
      when: docker_snap.rc == 0
